apiVersion: v1
kind: Service
metadata:
  name: svc-newcore-cms-carinfo-api
  namespace: cms-newcar-promotion-phil
  labels:
    version: dev
    product: newcore-cms-carinfo
spec:
  selector:
    app: newcore-cms-carinfo
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30612
---
apiVersion: v1
kind: Service
metadata:
  # name: svc-newcore-cms-carinfo-api-grpc
  name: svc-newcore-cms-carinfo-api-grpc
  namespace: cms-newcar-promotion-phil
  labels:
    version: dev
    product: newcore-cms-carinfo
spec:
  selector:
    app: newcore-cms-carinfo
  ports:
    - port: 81
      targetPort: 81
      protocol: TCP
      name: http
      
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newcore-cms-carinfo
  namespace: cms-newcar-promotion-phil
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: newcore-cms-carinfo
  template:
    metadata:
      labels:
        app: newcore-cms-carinfo
    spec:
      containers:
        - name: newcore-cms-carinfo
          image: sg.registry.nextgen-global.com/ap_ecosystem/v1.cms/api/carinfo/philkotse/production:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 81
          #          livenessProbe:
          #            httpGet:
          #              path: /car-sale
          #              port: 80
          #            initialDelaySeconds: 5
          #            periodSeconds: 3
          #          readinessProbe:
          #            httpGet:
          #              path: /car-sale
          #              port: 80
          #            initialDelaySeconds: 5
          #            periodSeconds: 3
          resources:
            limits:
              memory: "2048Mi"
              cpu: "2"
      imagePullSecrets:
        - name: regcred